server:
  port: 8081
      
spring:
  data:
    mongodb:
      host: localhost
      port: 27017            
      authentication-database: admin
      database: configuration
      username: admin
      password: password
            
---
server:
  port: 8081
 
spring:
  config:
    activate:
      on-profile: avib
  data:
    mongodb:
      host: avib-mongodb
      port: 27017
      authentication-database: admin
      database: configuration
      username: admin
      password: password          